### ISSUE TITLE
errors within example files

### ISSUE THREAD

**Issue by Tom-Shorter** [ga4gh-beacon/beacon-framework-v2#26]
There are a few errors/inconsistencies within the example files as listed below:

- beaconMapResponse-example.json and beaconConfigurationResponse-example.json are the same, I believe that the Map example is correct and the configuration example is incorrect.

- inconsistent requestedSchemas in meta sections - `{ "map": "beacon-map-v2.0.0-draft.3" }` in beaconMapResponse-example.json but `{ "entityType": "EntryTypeB", "schema": "entry-typeB-schema-v1.0"}` in beaconEntryTypeCoreResponse-MAX-example.json (there are multiple examples which show both types), `{ "entityType": "EntryTypeB", "schema": "entry-typeB-schema-v1.0"}` seems to be the correct method.

**Comment by jrambla** [comment]
The first one is solved in c3f71be
The second one is a side effect of how we do validations first and how we do it later (trying to make the folder structure more clear).
Initially we had copies of the schemas that were "strict" (setting additionalProperties: false), hence we can spot any deviation from the schema. However this led to have schemas in two folders: the actual, flexible ones and the strict ones. Also, synchronizing them was manual (I believe there is a way of solving this but haven't checked it).
We decided to remove the latter to avoid confusion, but I will be happy to bring it back if the general opinion is that they will be useful.
We also believed that everyone can mimic that locally if necessary.

Thoughts @Tom-Shorter @mbaudis @MrRobb ?

**Comment by Tom-Shorter** [comment]
Thanks for the info Jordi, I'm still not 100% clear on the second point but the main thing I take from it is that the validation process is causing a disparity between the examples and schemas. This could lead to confusion/incorrect implementations which seems pretty counter intuitive to what a validation process should be!

I'm probably missing something but I still think that if the examples do not match the schema then something is wrong somewhere.

**Comment by Tom-Shorter** [comment]
I'll add new things I find as a comment on this issue instead of making another issue:

`/requests/examples-fullDocuments/beaconRequestBody-MAX-example.json` contains the below request parameter:

```
    "requestParameters": {
      "datasets": {
        "datasetIds": ["DatasetXYZ", "Dataset123"]
      }
    }
```
the `datasets` model does not contain a `datasetIds` property, the examples should match the default models to avoid confusion This example implies you can search using more than one `datasetId` whereas this is not currently possible within the beacon spec.

**Comment by jrambla** [comment]
You are getting to the key question: "as the Framework is agnostic to the Model, should the Fmwk examples use one model as 'reference' for examples, or should they be completely unrelated to any Model"?.
I've opted for the second one, although probably using a generic dataset concept here and there to exemply collection types.
Thoughts?

**Comment by Tom-Shorter** [comment]
I don't think there's a problem with either method. The main thing is that if a model is used within an example somewhere then being able to go and look at that model, how it's defined within the schema and how that relates to the framework is extremely useful instead of having an abstract model which you can't find elsewhere.

Using the standard beacon models would be the simplest option and tie in the beacon models with the framework for anyone implementing a beacon but defining simple generic models within the framework itself might be a suitable alternative.
